CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    pay_day INTEGER NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_user_phone_number UNIQUE (phone_number)
);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revoked BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_refresh_token_token UNIQUE (token)
);

CREATE TABLE pockets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    monthly_limit NUMERIC(19, 4) NOT NULL,
    current_balance NUMERIC(19, 4) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    last_reset_at TIMESTAMP(6) WITH TIME ZONE,
    last_manual_override_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT chk_pocket_balance_non_negative CHECK (current_balance >= 0)
);

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pocket_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    amount NUMERIC(19, 4) NOT NULL,
    payee_upi_id VARCHAR(255),
    note VARCHAR(255),
    status VARCHAR(255) NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_transaction_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT transactions_status_check CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'FAILED'))
);
